### ISSUE TITLE
Google Docs "Suggestions"

### ISSUE THREAD

**Issue by jennybc** [ropenscilabs/googlestuff#10]
This might be really effing close to a pull request ..... which is **very** intriguing.

https://support.google.com/docs/answer/6033474?hl=en

https://www.youtube.com/watch?v=vytBjbfv9Qw

**Comment by jennybc** [comment]
Relevance to mixed team workflow: Short of full round trips, the Google Docs collaborator could possibly make suggestions. Perhaps these could be retrieved via API? and presented for consideration by the Rmd author. Or, very extreme, even presented as a pull request?

**Comment by noamross** [comment]
I've used this, it's nice.  In a round-trip scenario, one option is to simply accept the suggestions in the Google Doc, then pull the updated text back to your local version.  So far I'm not seeing any mention of Suggestions in the apps scripts documentation, so I'm not sure if one can access them directly.

**Comment by jennybc** [comment]
@noamross Then it's no different from the mythical round trips we are already contemplating in #2, right? Yeah, I didn't look into the apps script side of it, so if it's really not there, this is a dead end. It would be such a nice way to solve the diff problem, though, and, by definition, allows the Google Doc person to edit appropriate things, e.g. prose, vs. problematic bits, e.g. R source or Rmd infrastructure.

**Comment by jennybc** [comment]
Another idea I'll park here: it looks like there's a link between Google Doc Suggestions and Word Tracked Changes:

http://www.pcworld.com/article/2458445/google-docs-gains-better-track-changes-integration-with-microsoft-office.html

We already do Rmd --> docx --> Google Doc. So maybe some of inversion back through Word would yield a usable diff on the prose that could be applied to the Rmd?

I'm just trying to think of ways to round trip without directly solving the un-knitting problem. I've unpacked the XML that is an Excel sheet but have never thought about what lurks inside docx 😱. Maybe we could exploit [Pandoc's JSON representation of the AST](http://pandoc.org/scripting.html). This looks insane but just consider it: Rmd --> Pandoc AST as JSON --> docx --> Google Doc (edits as Suggestions)--> docx (with proposed edits somehow represented in track changes) --> Pandoc JSON --> diff with original JSON to get a diff that can be applied to the Rmd.

**Comment by noamross** [comment]
Honestly, there seems like enough zaniness there that I'd rather solve the unknitting problem.  Here's another brainstormed workflow:

1) We use custom knitr hooks to make our own, Jupyter-like intermediate format that clearly labels each part of the rendered document as text/source/output, includes chunk metadata and a unique ID.  This doc should be designed to be unknit.  (Within text sections, text may be represented as Pandoc JSON, or maybe the format is Pandoc JSON with additional attributes attached to sections.)

2) We use Apps Scripts to convert this to a Google Doc natively, adding the unique IDs and metadata to each element of the document as attributes

3) We also upload the intermediate document, and put a link to this as an attribute on the Google Doc.

4) On return trip, we pull down the Google Doc JSON format and our intermediate doc, and update the intermediate doc with changes to the text sections of the Google Doc, matching parts via unique IDs.

5) We unknit the intermediate doc.

This is just as crazy but the crazy here is in inventing new things rather than wrenching apart docx.

**Comment by jennybc** [comment]
"It may be crazy, but at least it's OUR crazy."

**Comment by jennybc** [comment]
The right answer might be to spend x time units on each approach and see which one seems to be yielding.

**Comment by jennybc** [comment]
I'll go ahead and close this since #2 exists and these are now linked anyway.
