### ISSUE TITLE
Using with Shiny Server (non-interactive)

### ISSUE THREAD

**Issue by DavidRGriswold** [ropenscilabs/googlestuff#11]
I have really enjoyed testing this library and would like to use it to enable google docs output for a program I am writing that has educators as an intended audience, since they are often on Google Apps systems. As written, however, it appears to be incompatible with Shiny Server and the online RStudio server - I think this is because of the way auth is done. Is that right? Do you think it would be possible to use something like the googleAuthR package to make this library work on Shiny and RStudio servers?

I'm happy to play around with this possibility if you think I'm correct that it might solve the problem.

**Comment by jennybc** [comment]
This was something of a "hackathon" experiment that hasn't advanced since. In theory, auth can be worked out for Shiny, but, yes, that's definitely not true at the moment. Basically ... I send you good vibes and good luck! 🙂 And agree that googleAuthR is currently the best place to go. I'm involved in another package that's developing re: Google auth but it's certainly not as mature and has not yet addressed Shiny.

**Comment by DavidRGriswold** [comment]
All  right, thanks!

**Comment by maelle** [comment]
This package was an experiment at an unconf and its development has stopped. The repo will become read-only.
