### ISSUE TITLE
Google Apps Script link

### ISSUE THREAD

**Issue by jennybc** [ropenscilabs/googlestuff#4]
@nicolewhite Could you add a link here to the script? And/or just drop the source in? I'd like to be able to turn that feature on again or extend it. Basically, before it gets lost in the sands of time, can you do a brain dump on what you learned about this?

**Comment by nicolewhite** [comment]
Oh yes, sorry about that. Had to miss Friday because of work. Here's the code:

``` javascript
function saveRMarkdown(google_doc_id, raw_r_markdown) {
  var google_doc = DocumentApp.openById(google_doc_id);
  var markdown_doc_name = google_doc.getName() + "-r_markdown";
  var markdown_doc = DocumentApp.create(markdown_doc_name);
  markdown_doc.appendParagraph(raw_r_markdown);

  var markdown_doc_id = markdown_doc.getId();

  updateFileProperty(markdown_doc_id, "google_doc_id", google_doc_id);
  updateFileProperty(google_doc_id, "markdown_doc_id", markdown_doc_id);

  return markdown_doc_id;
}

function updateFileProperty(id, key, value) {
  var property = {
    key: key,
    value: value,
    visibility: "PUBLIC"
  }

  Drive.Properties.insert(property, id);
}
```

It appears that Apps Script wasn't built for collaboration; this code is attached to the doc that I happened to start the script editor in, even though it isn't bound to that doc or related to it in any way. The doc is here and you can request access: https://docs.google.com/document/d/1aiMgZnRX2xW2MD29FJiPOQtJI8FqmNDTr9f-RQzf1pQ/edit?usp=sharing

Once you have access, you can edit the script by going to Tools -> Script editor. It is currently deployed as an "API executable," so that it can be executed through the Execution API. Once you create a script, you save it as a "Project" and this project becomes an app that you control through the Google Developer Console. You have to enable the Execution API and any of the APIs listed under the script's scope: File -> Project Properties -> Scopes. After making any changes to the script, you have to re-publish the script under Publish -> Deploy as API executable. After publishing, it shows you the script's ID, which is needed to call the script via the Execution API.
